### ISSUE TITLE
Playback does not always work on startup.

### ISSUE THREAD

**Issue by yrammos** [DCMLab/mozartDiceGame#11]
Is this a delay or independent of time? Anyhow, playback does not seem to work on application startup. An unknown series of UI actions (or an unspecified amount of wait time) seem to be needed for playback to work.

**Comment by XinyiDyee** [comment]
When I click play button on startup, DevTools report "AudioContext is disabled from starting automatically".  This should be due to the autoplay policies of modern browsers. The browsers require user interaction before audio can be played. If audio playback is triggered by user interaction, such as clicking a button, this issue can be solved. So we can keep "Enter" button on all devices.

**Comment by yrammos** [comment]
Indeed, as far as I know this restriction is enabled by default on all modern browsers. I think the Enter button is amply sufficient. Closing, thanks!
